[package]
name = "jorzacan_postbuild"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jorzacan = { version = "0.1.0", path = "../jorzacan" }
man = "0.3.0"